In [147]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeCV,LassoCV,LinearRegression,RidgeCV,LassoCV,ElasticNet,ElasticNetCV,Lasso,Ridge
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from pandas_profiling import ProfileReport

In [82]:
data=pd.read_csv("Admission_Prediction.csv")

In [83]:
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1      337.0        118.0                4.0  4.5  4.5  9.65   
1           2      324.0        107.0                4.0  4.0  4.5  8.87   
2           3        NaN        104.0                3.0  3.0  3.5  8.00   
3           4      322.0        110.0                3.0  3.5  2.5  8.67   
4           5      314.0        103.0                2.0  2.0  3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [36]:
pf=ProfileReport(data)

In [7]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [85]:
data["GRE Score"]=data["GRE Score"].fillna(data["GRE Score"].mean())

In [86]:
data["TOEFL Score"]=data["TOEFL Score"].fillna(data["TOEFL Score"].mean())

In [87]:
data["University Rating"]=data["University Rating"].fillna(data["University Rating"].mean())

In [88]:
data.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [89]:
data.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [90]:
data.drop(["Serial No."],axis=1,inplace=True)

In [91]:
data

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [92]:
Y=data["Chance of Admit"]

In [97]:
X=data

In [98]:
X

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [99]:
Y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [100]:
X

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [101]:
scaler = StandardScaler()

In [102]:
scaled_data=scaler.fit_transform(X)
scaled_data

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [103]:
scaled_dataframe=pd.DataFrame(scaled_data)


In [104]:
profile=scaled_dataframe.profile_report()
profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [105]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [107]:
scaled_dataframe.isna().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [108]:
# Vif is to calculate multicollineatity between features
vif_df=pd.DataFrame()


In [111]:
vif_df["vif"]=[variance_inflation_factor(scaled_dataframe,i) for i in range(scaled_dataframe.shape[1])]
vif_df["feature"]=X.columns

In [112]:
vif_df

vif            feature
0  4.153268          GRE Score
1  3.792866        TOEFL Score
2  2.508768  University Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

In [118]:
scaled_data

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [124]:
X_train,X_test,Y_train,Y_test=train_test_split(scaled_data,Y,test_size=0.25)

In [125]:
# Creating model
lr=LinearRegression()

In [126]:
lr.fit(X_train,Y_train)

LinearRegression()

In [129]:
import pickle
pickle.dump(lr,open("practice_linear_admission.pickle","wb"))

In [134]:
lr.predict([[337.0000000,117.5,4.6,4.9,4.8,9.02,1]])

array([10.25336952])

In [136]:
test1=scaler.transform([[337.0000000,117.5,4.6,4.9,4.8,9.02,1]])

In [137]:
test1

array([[1.84274116, 1.70583312, 1.310975  , 1.54139527, 1.42343572,
        0.73411844, 0.88640526]])

In [138]:
lr.predict(test1)

array([0.8796552])

In [ ]:
# This is because we completely changed the range with standard Scaler

In [139]:
# Optimization Steps
lr.score(X_test,Y_test)

0.8501230551753614

In [140]:
def adjacent_R2_Score(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2


In [141]:
adjacent_R2_Score(x_test,y_test)

0.7927616547701901

In [142]:
lr.intercept_

0.7198180470544042

In [143]:
lr.coef_

array([0.02082569, 0.01470198, 0.00524839, 0.00155136, 0.01612312,
       0.0740123 , 0.0110851 ])

In [144]:
lassocv=LassoCV(cv=10,max_iter=200000,normalize=True)
lassocv.fit(X_train,Y_train)

LassoCV(cv=10, max_iter=200000, normalize=True)

In [145]:
lassocv.alpha_

1.5922288974512038e-05

In [148]:
lasso=Lasso(alpha=lassocv.alpha_)
lasso.fit(X_train,Y_train)

Lasso(alpha=1.5922288974512038e-05)

In [149]:
lasso.score(X_test,Y_test)

0.8501098996606263

In [150]:
ridgecv=RidgeCV(alphas=(0.1,1.0,10.0),cv=10,normalize=True)
ridgecv.fit(X_train,Y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=10, normalize=True)

In [151]:
ridgecv.alpha_

0.1

In [154]:
ridge_lr=Ridge(alpha=ridgecv.alpha_)

In [155]:
ridge_lr.fit(X_train,Y_train)

Ridge(alpha=0.1)

In [156]:
ridge_lr.score(X_test,Y_test)

0.8501291659725108

In [158]:
elastic=ElasticNetCV(alphas=None,cv=10)
elastic.fit(X_train,Y_train)

ElasticNetCV(cv=10)

In [159]:
elastic.alpha_

0.0005801586682669168

In [160]:
elastic.l1_ratio_

0.5

In [163]:
elastic_lr=ElasticNet(alpha=elastic.alpha_,l1_ratio=elastic.l1_ratio_)
elastic_lr.fit(X_train,Y_train)

ElasticNet(alpha=0.0005801586682669168)

In [164]:
elastic_lr.score(X_test,Y_test)

0.8498859504293994